---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: capi-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  version: v1.4.1
  deployment:
    containers:
    - name: manager
  manager:
    featureGates:
      "MachinePool": true
      "ClusterResourceSet": false
      "ClusterTopology": true
      "RuntimeSDK": false
      "LazyRestmapper": false
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: InfrastructureProvider
metadata:
  name: azure
  namespace: capz-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  version: v1.8.2
  deployment:
    containers:
    - name: manager
  manager:
    featureGates:
      "MachinePool": true
      "AKSResourceHealth": false
      "EdgeZone": false
  secretName: cluster-identity-secret