apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: capz-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: management
        url: https://kubernetes.default.svc
        workload-cluster: worker4
      - cluster: management
        url: https://kubernetes.default.svc
        workload-cluster: worker5
      - cluster: management
        url: https://kubernetes.default.svc
        workload-cluster: worker6
      - cluster: management
        url: https://kubernetes.default.svc
        workload-cluster: worker7
  template:
    metadata:
      name: '{{workload-cluster}}'
    spec:
      project: clusters
      source:
        repoURL: 'https://joaquinrz.github.io/capi-gitops'
        targetRevision: 0.0.5
        chart: capi-aks
        helm:
          values: |
            controlAgentPoolNodeSize: Standard_B4ms
            workerAgentPoolNodeSize: Standard_B4ms
            sshPublicKey: "c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFESU94Zytnb1NZb0NJTkQzSUlBalBvUEdyN2dzdXg5T1FqRTVJUDJ3RVU4ZU1zeXdnR1hCd1pYVVZqaDhOZ0ZIVldaRU1UUUNBTTUyUDJpcFlCdXA5UWh1cVdWakg0djBocmoxWC9yeDd0emxaaDJ3azNrZ1ZQUXdNS0N5YWNRTGlmcXVzNHF1SkxTUUFQdTFrc2d4YVdFQlduU2EwZStETTJEMFBZcy9qMjg0cU9POVQ5VUxxcGIvWkpLOWd5U2ErQWZTTWhHQ3NrY1QvRWZFOGcxaXFDOTZQYWpGeEdIT0J4cWlERnRJS1BoTmlxS1lydURoVkpZbWhBWEc2U2NIYWRpWHpQM0JkaVBSNjZleUNPUXRTZUl4am5FZUpjclo3dlpMRnBXUXZhYVp3K0pmUGtHR0ZDc0JUbjM5ZGZyMWF3ck10UElQdmtqNGlVMWprR0t6VUQgYWxlc3NhbmRyb0BBbGVzc2FuZHJvcy1NQlAuZnJpdHouYm94"
            location: westeurope
            name: '{{workload-cluster}}'
            subscriptionId: 1c51d1c3-d83d-4d71-ace1-df3496eddac4
      destination:
        server: '{{url}}'
        namespace: '{{workload-cluster}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
