apiVersion: v1
kind: Namespace
metadata:
    name: prometheus
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: prometheus
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: infra
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts/'
    targetRevision: "45.10.1"
    chart: kube-prometheus-stack
    helm:
      valueFiles:
      - $values/gitops/management/monitoring/prometheus/prometheus-values.yaml
  - repoURL: https://github.com/joaquinrz/capi-gitops.git
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
    retry:
      limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
