configs:
  rbac:
    policy.default: 'role:readonly'
  cm:
    users.anonymous.enabled: "true"
    timeout.reconciliation: 10s
  params:
    server.insecure: true
    application.namespaces: "*"
  repositories:
    gitops:
      url: https://github.com/joaquinrz/capi-gitops.git
      name: gitops
      type: git