apiVersion: v1
kind: Namespace
metadata:
    name: external-dns
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: external-dns
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: infra
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 6.18.0
    chart: external-dns
    helm:
      valueFiles:
      - $values/gitops/management/networking/external-dns/external-dns-values.yaml
  - repoURL: https://github.com/joaquinrz/capi-gitops.git
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
