apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vclusters-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: management
        url: https://kubernetes.default.svc
        workload-cluster: vcminion1  
  template:
    metadata:
      name: '{{workload-cluster}}'
    spec:
      project: clusters
      source:
        repoURL: 'https://charts.loft.sh/'
        targetRevision: 0.15.0
        chart: vcluster-k8s
        helm:
          values: |
            sync:
              ingresses:
                enabled: true
            mapServices:
              fromHost:
              - from: thanos/thanos-receive
                to: thanos/thanos-receive
      destination:
        server: '{{url}}'
        namespace: '{{workload-cluster}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
