apiVersion: v1
kind: Namespace
metadata:
    name: grafana
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: grafana
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: infra
  sources:
  - repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: "6.53.0"
    chart: grafana
    helm:
      valueFiles:
      - $values/gitops/management/monitoring/grafana/grafana-values.yaml
  - repoURL: https://github.com/joaquinrz/capi-gitops.git
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-dashboards
  namespace: grafana
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: "gitops/management/monitoring/dashboards"
    targetRevision: main
    directory:
      recurse: true
    repoURL: https://github.com/joaquinrz/capi-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
