apiVersion: v1
kind: Namespace
metadata:
    name: cert-manager
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: infra
  sources:
  - repoURL: 'https://charts.jetstack.io'
    targetRevision: "v1.11.1"
    chart: cert-manager
    helm:
      valueFiles:
      - $values/gitops/management/networking/cert-manager/cert-manager-values.yaml
  - repoURL: https://github.com/joaquinrz/capi-gitops.git
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer
  namespace: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: infra
  sources:
  - repoURL: 'https://charts.adfinis.com'
    targetRevision: "0.2.5"
    chart: cert-manager-issuers
    helm:
      valueFiles:
      - $values/gitops/management/networking/cert-manager/cluster-issuer-values.yaml
  - repoURL: https://github.com/joaquinrz/capi-gitops.git
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
