apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-secret-capz
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  generateExistingOnPolicyUpdate: true
  rules:
  - name: sync-secret-capz
    match:
      any:
      - resources:
          names:
          - "*kubeconfig"
          kinds:
          - Secret
    exclude:
      any:
      - resources:
          namespaces:
          - kube-system
          - kube-public
          - kyverno
    context:
    - name: data
      variable: 
        value: "{{ request.object.data }}"

    - name: dataConfig
      variable:
        value: |
          {
            "bearerToken": "{{ bearerToken }}",
            "tlsClientConfig": {
              "insecure": false,
              "caData": "{{ caData }}"
            }
          }          
        jmesPath: 'to_string(@)'
    generate:
      synchronize: true
      apiVersion: v1
      kind: Secret
      name: "{{ clusterPrefixedName }}"
      namespace: argocd
      data:
        type: Opaque
        data:
          name: "{{ clusterPrefixedName | base64_encode(@) }}"
          server: "{{ serverName | base64_encode(@) }}"
          config: "{{ dataConfig | base64_encode(@) }}"
