{
 "title": "IMDb App",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(ImdbAppSummary{},cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ImdbAppDuration_count{cluster=~\"$cluster\"}[1m])) by (mode)",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "IMDb App",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ImdbAppDuration_count{cluster=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(ImdbAppDuration_bucket{cluster=~\"$cluster\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ImdbAppDuration_count{code != \"OK\",cluster=~\"$cluster\"}[1m])) by (mode)",
     "legendFormat": "{{category}}"
    }
   ]
  }
 ]
}