apiVersion: v1
kind: Service
metadata:
  name: prometheus-sample-app
  labels:
    app: prometheus-sample-app
spec:
  type: ClusterIP
  selector:
    app: prometheus-sample-app
  ports:
  - port: 8080
    name: http